services:
  # Contêiner da Aplicação Web / API (FrankenPHP)
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cobeb_api
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APP_ENV=development # ou local
      - REVERB_HOST=reverb
    # O FrankenPHP será executado automaticamente pelo CMD do Dockerfile

  # Contêiner do WebSockets (Laravel Reverb)
  reverb:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cobeb_reverb
    restart: unless-stopped
    command: php artisan reverb:start --host="0.0.0.0" --port=8080
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=development
    depends_on:
      - api

  # Contêiner de Processamento de Filas (Laravel Queue)
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cobeb_queue
    restart: unless-stopped
    # Executa o worker para escutar a fila padrão
    command: php artisan queue:work --tries=3 --timeout=90
    environment:
      - APP_ENV=development
    depends_on:
      - api
