name: Deploy para Coolify

on:
  push:
    branches: [main, develop]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Deploy Produção via Coolify
        if: github.ref == 'refs/heads/main'
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_PROD }}'

      - name: 🧪 Deploy Homologação via Coolify
        if: github.ref == 'refs/heads/develop'
        run: |
          curl --request GET '${{ secrets.COOLIFY_WEBHOOK_STAGING }}'
